### ISSUE TITLE
折叠内容里的链接在展开内容后不会被替换

### ISSUE THREAD

**Issue by gloomy-ghost** [paicha/zhihu-undirect#2]
比如说给一个有外部链接的答案点了赞，翻自己timeline时展开那个答案的话链接依然要到link.zhihu.com溜一圈

**Comment by paicha** [comment]
知乎的「我的主页」做了一次改版，去掉了 jQuery ，导致脚本报错了。
重构了一下，不再依赖 jQuery，已经发布了。
